FROM docker.io/python:3.10@sha256:09447073b9603858602b4a725ad92e4fd4c8f6979768cee295afae67fd997718 as algorand-contracts-build

RUN python3 -m pip install virtualenv
COPY Pipfile.lock Pipfile.lock
COPY Pipfile Pipfile

RUN python3 -m pip install pipenv
RUN pipenv install
RUN mkdir teal
COPY *.py .

RUN pipenv run python3 admin.py --mainnet --genTeal 

FROM scratch AS algorand-contracts-export
COPY --from=algorand-contracts-build /teal/* .


